### PR TITLE
LPS-57392

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@jkappler basically, the word "Page" is what is shown the user. The word "Layout" is what we use in the backend to describe a Page.

We have LayoutPrototype, LayoutSet, etc. PageSet would be confusing. We need a name in the backend that is "Layout" based.

Thx.

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29073. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/29152. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
