### PR TITLE
[TECHNICAL SUPPORT] LPS-106070

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-106070

AssetDisplay layouts are not added to manifest.xml, so in order to import portlet configuration we should force it, ignoring manifestSummary (see https://github.com/jkappler/liferay-portal/pull/657/commits/892be990fa724212aa00b0bd6a1b11e4ac3f04a2)

Root cause of this:

- `importPortletControlsMap` is calculated using "portlet-configuration" attribute of portlet entry inside Layout element from **manifest.xml**
- But in case of AssetDisplay layouts, the Layout entry is added to **/group/35632/portlet/com_liferay_layout_admin_web_portlet_GroupPagesPortlet/0/portlet-data.xml** file because it is not a real Layout.

Other solutions to this issue whould be:

- **Option 1:** At export time, change export code in order to include Layout entry at manifest.xml level
- **Option 2:** At import time, change import code in order to read Layout entry from portlet-data.xml file.

Nevetheless, I think both solutions are more difficult to implement than just ignoring manifestSummary variable setting it to null.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jorgediaz-lr** [comment]
It was send to Brian: https://github.com/brianchandotcom/liferay-portal/pull/83833

💩 💩 💩

**Pull request closed without merging**
