### PR TITLE
[TS] LPS-110319 Use ServiceContextThreadLocal to set "readOnly" mode to true during embedded portlet rendering

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-110319

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
@jorgediaz-lr @jkappler you need to add try finally, if something happens we are going to have readOnly always true

**Comment by ealonso** [comment]
@jorgediaz-lr @jkappler 
What happen with fragments and other templates that uses freemarker?

**Pull request closed without merging**
