### PR TITLE
Lps 103676 2

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:

> https://issues.liferay.com/browse/LPS-103676
> 
> **Issue**:
> URL defined for Embedded Page is not a valid URL by itself.
> 
> **Solution**:
> URL configuration of Embedded Pages automatically prepends the URL with "http://" or "https://" when it's not starting with it and is not a friendly URL. The inputted URL is compared to friendly URLs of all layouts. This is done by getting all layouts within the company and if the strings (`friendlyURL` and `src`) match, the boolean `isFriendlyURL` is set to true. If true, it would not prepend the protocol; otherwise, it would prepend the protocol and set it within the form's type setting properties as `embeddedLayoutURL`.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:relevant:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Hello, @jkappler,

Do you know when you will have a chance to review this?

**Comment by jkappler** [comment]
@SamZiemer, I was at devcon and I'm ooo until Monday

@ealonso, @pavel-savinov

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@knchau, @SamZiemer listing all layouts might lead to performance issues. We could have sites with hundreds (or thousands) of layouts. Can we find another way of doing this? I can take a look at it next week, Tuesday/Wednesday. Let me know please.

Thanks for the patience

**Comment by knchau** [comment]
See updated PR here: https://github.com/jkappler/liferay-portal/pull/639

I would appreciate your further input. Thank you!

**Pull request closed without merging**
