### PR TITLE
LPS-63004 SF

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@brianwulbern, same PR as the one from @evannagayama here > https://github.com/evannagayama/liferay-portal/pull/526

Compiles just fine, let's see what errors we get

**Comment by brianwulbern** [comment]
@jkappler 

Thanks!  I'll keep an eye out.

**Comment by brianwulbern** [comment]
Still an NPE and Sites aren't available for adding :/

after0

**Comment by jkappler** [comment]
Will resend to @brianwulbern

**Comment by brianwulbern** [comment]
Hi Juergen,

Sorry, lots of pr-tester issues today, I'll look at this first thing tomorrow :)

Brian

**Pull request closed without merging**
