### PR TITLE
LPS-87351 We should use the uuid, even if the link has an anchor.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65118. [See changes here.](https://github.com/jkappler/liferay-portal/compare/fbe02225492b~2...fbe02225492b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65119. [See changes here.](https://github.com/jkappler/liferay-portal/compare/0386b58c664b~2...0386b58c664b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
