### PR TITLE
LPS-93586 Deduplicating logic

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72061. [See changes here.](https://github.com/jkappler/liferay-portal/compare/4507ec0ee4d5~2...4507ec0ee4d5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
