### PR TITLE
LPS-110376 Use constants

### PR DESCRIPTION
**Pull request by dacousalr**
\cc @bakayattila

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/jkappler/liferay-portal/pull/752

**Pull request closed without merging**
