### PR TITLE
LPS-94286 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-94286

### CODE REVIEW

**Comment by kyle-miho** [comment]
Testing here: https://github.com/kyle-miho/liferay-portal/pull/172

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/173. [See changes here.](https://github.com/jkappler/liferay-portal/compare/e0a9a45d451c~2...e0a9a45d451c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/174. [See changes here.](https://github.com/jkappler/liferay-portal/compare/1dd7147ae69b~4...1dd7147ae69b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
