### PR TITLE
LPS-104183 & LPS-104184

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
@sandrodw3 Can you verify that the new editor works correctly with `modules/apps/layout/layout-page-template-service/src/test/resources/com/liferay/layout/page/template/internal/util/dependencies/expected_layout_data_v1_complete.json?

**Comment by ruben-pulido** [comment]
@jkappler We should not merge the last commit (43501b0) until the new editor is ready

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by diegonvs** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
already merged, thx

**Pull request closed without merging**
