### PR TITLE
Revert "LPS-91367 - Updating Alloy 3.1.x to 25b0e99ce5db7d3e0101e27f329ff104f5101423"

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by sandrodw3** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
Just started reviewing :)

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
merged, thanks

**Pull request closed without merging**
