### PR TITLE
LPS-77805 Avoid redirect to add_fragment_entry by default

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55160. [See changes here.](https://github.com/jkappler/liferay-portal/compare/efe0c60~2...efe0c60) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55161. [See changes here.](https://github.com/jkappler/liferay-portal/compare/398fbab~2...398fbab) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
