### PR TITLE
LPS-57521 The getType method should return the _type attribute, honoring the methods that invoke it

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
ci:retest

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/epgarcia/liferay-portal/pull/411. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/30108. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
