### PR TITLE
LPS-92496 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-92496

### CODE REVIEW

**Comment by kyle-miho** [comment]
Hey @jkappler these aren't done, but if you happen to have some extra time, could you check: 
public void testDeleteSiteNavigationMenuWithoutPermissions() / WithPermissions()? (also applies to all other methods that use  "ModelResourcePermission<SiteNavigationMenu>"
I am getting a NoResourceFoundException , but I am pretty sure this is correct: ResourcePermissionLocalServiceUtil.addResourcePermission(
			_company.getCompanyId(),
			"com.liferay.site.navigation.model.SiteNavigationMenu", 
			ResourceConstants.SCOPE_GROUP, String.valueOf(_group.getGroupId()),
			siteMemberRole.getRoleId(), ActionKeys.DELETE);

**Comment by kyle-miho** [comment]
I followed https://github.com/liferay/liferay-portal/blob/master/modules/apps/segments/segments-test/src/testIntegration/java/com/liferay/segments/service/test/SegmentsEntryServiceTest.java
as an example for help

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/167. [See changes here.](https://github.com/jkappler/liferay-portal/compare/e5c78633ee39~6...e5c78633ee39) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
