### PR TITLE
LPS-109985 Baseline

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @jkappler,

Source formatting is marking the parameter of type HttpServletRequest in the new method as something to avoid. However, this interface has the method matches with a parameter of the same type.

I would prefer to keep as it is but if it is needed, I can change it.

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
