### PR TITLE
Lps 103676

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

Notes from Kim:

> https://issues.liferay.com/browse/LPS-103676
> 
> **Issue**:
>  URL defined for Embedded Page is not a valid URL by itself. 
> 
> **Solution**:
> URL configuration of Embedded Pages automatically prepends the URL with "http://" or "https://" when it's not starting with it.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
this was resent to me here: https://github.com/jkappler/liferay-portal/pull/637

**Pull request closed without merging**
