### PR TITLE
Lps 86235 echo

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @jkappler 

There are several portlets that are non deployable but has property set to PreferencesUniquePerLayout=true(the default value), I believe these following portlets belong to prod team echo? Would you help review them.

This commit explicitly set it to false.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
hi @arthurchan35, sorry for the delay in the response, will review it first thing in the morning. 

Could you please send future PRs to @liferay-echo user in case I'm not able to review them? That way the whole team will be aware of them. 

Thanks a lot

**Comment by arthurchan35** [comment]
Hi @jkappler ,
Sure, I will send furture PRs to @liferay-echo. I was not aware of PR changes before.

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
it's okay @arthurchan35, we are just communicating it as we receive the PRs. Mostly if someone is not available, another person from the team could review the pull

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
