### PR TITLE
LPS-110789 Set approved status for imported page template layout

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
PR here: https://github.com/jkappler/liferay-portal/pull/735

**Pull request closed without merging**
