### PR TITLE
LPS-118310 Use info framework instead of layout asset entry

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by jkappler** [comment]
@jcampoy, @marianoalvarosaiz, waiting on LPS-114731 for this one

**Comment by marianoalvarosaiz** [comment]
thanks for the update @jkappler!

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
