### PR TITLE
LPS-128604 Adapt item selector to show only items with a Display Page associated for Web Contents

### PR DESCRIPTION
**Pull request by ruben-pulido**
//CC @ealonso @sandrodw3

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
