### PR TITLE
LPS-97542 using imported asset display page entry

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Hi @linolaoj, still getting the same issues as in the other pull. I'll take a more in depth look at it tomorrow. Sorry for the delay, just want to finish something I'm working on

**Comment by jkappler** [comment]
Sent already here: https://github.com/brianchandotcom/liferay-portal/pull/75867

**Pull request closed without merging**
