### PR TITLE
LPS-79951 Custom title must have higher priority than the layout name

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1611. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
