### PR TITLE
LPS-107685 Don't set pageElements if it is empty

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
Goes on top of https://github.com/brianchandotcom/liferay-portal/pull/84586

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Already merged to master (https://github.com/brianchandotcom/liferay-portal/pull/84681)

**Pull request closed without merging**
