### PR TITLE
LPS-110792 Add test for import of page template with fragment with editable field of type link

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
bundled here: https://github.com/jkappler/liferay-portal/pull/742

**Pull request closed without merging**
