### PR TITLE
LPS-89322 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-89322

### CODE REVIEW

**Comment by kyle-miho** [comment]
cc:// ealonso
This occurs because the changes here: https://github.com/brianchandotcom/liferay-portal/pull/66725/commits/c2f029bd7f43a3c320495f1ca09332aa55a494a3

got overwritten here
https://github.com/liferay/liferay-portal/commit/9a2a13d5a78c322e57f122581d1884556ee14909

So i reapplied Jurgen's changes. I tested this and it works now (Both with Recyclebin Enabled/Disabled and WC Folders / Articles). Let me know if the changes look good though!

**Comment by jkappler** [comment]
@kyle-miho, thanks for this! @ealonso has already the fix applied and was going to send it today

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/66957. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
