### PR TITLE
LPS-96593 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-96593

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by kyle-miho** [comment]
Copying over comments from our chat in case you didn't read

FYI: issues were, when removing a permission (this is more realistic than deleting it from the DB), we ideally want to add the permission back.
Theres a setResourcePermission service I used (The parameters were hard to figure out, had to use debugger to find out the correct string)
I use set because its the best way to reset the permission back to what it was originally, basically update the bitwise value back
This is what i decide to do when i remove a permission, to update it the value back, because adding a new permission will either 1) create a duplicate DB entry, or 2) create clutter since the old one with no permissions will not exist
I use deletePermission, to clean up any added permissions within a group scope, since it makes sense that we no longer want those permissions in the DB table once we destroy the group, otherwise removeResourcePermission will leave empty permissions in the DB table
Mainly because I prefer to keep what happens before and after the test the same, in the case that these testCases get run together with other testCases from another module, to prevent risks.

----------------------------
I didn't really do any SF to the testcases as a whole, since that will take a while, and these affect integration tests from passing, maybe we should look into fixing any SFs as a seperate task.

For example, instead of doing withPermissions test, still test the service normally, but while testing the functionality just in case someone changes it by mistake

**However the permissions don't seem to delete upon groupDeletion
so we end up with a bunch of extra permissions in the db**

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/378. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
