### PR TITLE
LPS-99973, LPS-89065

### PR DESCRIPTION
**Pull request by ryannealeigh**
https://issues.liferay.com/browse/LPS-99973
https://issues.liferay.com/browse/LPS-89065

Previous pull: https://github.com/jkappler/liferay-portal/pull/577

### CODE REVIEW

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:sf

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ryannealeigh** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Hey @jkappler 

What is the current status of this??

We need this to be merged in order to backport this to 7.1.x because mantain the current hotfixes is causing problems to us.

Thanks!!

**Pull request closed without merging**
