### PR TITLE
Updated MSBFragmentNameEditor for fragment updating

### PR DESCRIPTION
**Pull request by p2kmgcl**
Now a fragmentEntryId and an initialValue attributes can be specified
for updating an existing fragment instead of creating a new one

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/12. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/15. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
