### PR TITLE
LPS-112137 These contributed collections contain navigation widget so we have to make sure that widget alias is ready

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@jkappler @pavel-savinov seeing this issue in multiple PRs this morning. In light of the [current GitHub issues](https://liferay.slack.com/archives/C19PWQ74J/p1587649789303900), how would you feel about forwarding this directly to BChan?

**Comment by jpince** [comment]
Examples:
https://github.com/liferay-echo/liferay-portal/pull/373#issuecomment-618361537
https://github.com/liferay-echo/liferay-portal/pull/369#issuecomment-618406826
https://github.com/wincent/liferay-portal/pull/226#issuecomment-618358196

**Comment by pyoo47** [comment]
This was caused by a broken slave node. I've taken it offline so it shouldn't cause any more problems. I think it's ok to try again.

**Comment by jpince** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:forward

**Pull request closed without merging**
