### PR TITLE
LPS-83599 Do not change plid for embedded Asset Publisher portlets

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test

**Comment by dacousalr** [comment]
ci:retest

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61500. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
