### PR TITLE
LPS-92024 Add integration tests to cover bug

### PR DESCRIPTION
**Pull request by kyle-miho**

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69525. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/69527. [See changes here.](https://github.com/jkappler/liferay-portal/compare/cd69cb9ba54d~1...cd69cb9ba54d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
