### PR TITLE
[TECHNICAL-SUPPORT] LPS-88864

### PR DESCRIPTION
**Pull request by jonathanmccann**
@jkappler,

I'm not sure if the use case presented on LPS-88864 should be supported but this is how it worked in 7.0. Also, please let me know if you think the fix belongs somewhere else.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ccing @ealonso since I'm ooo until Thursday @jonathanmccann

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
