### PR TITLE
LPS-90801

### PR DESCRIPTION
**Pull request by jcampoy**

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2179. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
