### PR TITLE
LPS-86627

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @hhuijser, @daviddotzhang, I'm ooo for the moment (at the devcon). Just a thing about the change: if we set to true, won't we lose also other asset types? 

cc:// @ealonso

**Comment by daviddotzhang** [comment]
@jkappler yes, the asset types with "not selectable" will not show.  

the fixed behavior is the same as asset publisher. see it here https://issues.liferay.com/secure/attachment/287109/asset-publiser.png

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
hi @daviddotzhang, I was checking asset publisher and it's done a bit different. If all is the same, then I'll change AP to match this pattern. I'll try to send it tomorrow

**Comment by daviddotzhang** [comment]
@jkappler May I know the process of your new fix?

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64894. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
@daviddotzhang, as I mentioned, I was ooo. I returned today to the office. The PR was sent here: https://github.com/brianchandotcom/liferay-portal/pull/64894

**Pull request closed without merging**
