### PR TITLE
LPS-83315 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-83315

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
@jkappler I noticed that fragmentCollection also does this so I followed suit:
```
Assert.assertNull(
	FragmentEntryServiceUtil.fetchFragmentEntry(
		fragmentEntry1.getFragmentEntryId()));
//This is to check that we actually deleted the fragment entries
```
after we technically already deleted the Fragment Entry / Collection. 
`FragmentEntryServiceUtil.deleteFragmentEntries(fragmentEntryIds);`

Would it be safer if we used the previously array-stored id instead? Something like
```
Assert.assertNull(
	FragmentEntryServiceUtil.fetchFragmentEntry(
		fragmentEntryIds[0]));
```
I am assuimg that deleteFragmentEntries deletes the fragmentEntry1 and fragmentEntry2 objects, so we shouldn't be calling their methods anymore. However, the old methods still pass, so maybe Java deletes things at the end of the scope instead of upon call (like C++).

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61238. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61239. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
