### PR TITLE
LPS-101826 Add recent asset when selecting the asset

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78544.

**Comment by jkappler** [comment]
Already sent to BChan

**Pull request closed without merging**
