### PR TITLE
LPS-104142 Test sendRedirect with context

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
//cc @jorgediaz-lr

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
merged, thx

**Comment by jkappler** [comment]
already merged, thx

**Pull request closed without merging**
