### PR TITLE
LPS-90307 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-90307

### CODE REVIEW

**Comment by kyle-miho** [comment]
Got this error after commiting the last commit, so not sure if related. Testing here https://github.com/kyle-miho/liferay-portal/pull/141

```
com.liferay.fragment.service.test.FragmentEntryServiceTest > classMethod STARTED

com.liferay.fragment.service.test.FragmentEntryServiceTest > classMethod FAILED
    java.lang.NullPointerException
        at com.liferay.arquillian.extension.junit.bridge.container.remote.LiferayRemoteDeployableContainer.undeploy(LiferayRemoteDeployableContainer.java:133)
        at com.liferay.arquillian.extension.junit.bridge.container.ContainerDeployController.undeploy(ContainerDeployController.java:125)
```

**Comment by kyle-miho** [comment]
The assertions in these tests are more deep because I want to rely on the backend service test to make our poshi test for this more stable and just assert that a new fragment entry of name X is created within Page > Page Fragments (Don't have to check in page editor).

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67974. [See changes here.](https://github.com/jkappler/liferay-portal/compare/370ecbdafb6f~1...370ecbdafb6f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
