### PR TITLE
[TS] LPS-106908

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-106908
https://issues.liferay.com/browse/PTR-1431

Solution was discussed in PTR-1431 with @dacousalr.  Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
sent fix to @dacousalr.

**Pull request closed without merging**
