### PR TITLE
LPS-108412 Workflow instance must be started using current user id, not the owner id

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@pavel-savinov just use `ci:test:sf` and `ci:test:relevant`. `relevant` will run stable also

**Comment by jpince** [comment]
@pyoo47 @yichenroy I see this error in the failing batches, looks unrelated?
```
ERROR: Build step failed with exception
com.fasterxml.jackson.core.JsonParseException: Unexpected character (',' (code 44)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (InputStreamReader); line: 7, column: 1297]
```

**Comment by yichenroy** [comment]
ci:test:relevant

@jpince @pavel-savinov restarting test since the error in stable batches look unrelated:
```
ERROR: Build step failed with exception
com.fasterxml.jackson.core.JsonParseException: Unexpected character (',' (code 44)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (InputStreamReader); line: 7, column: 1297]
```
See discussion: https://liferay.slack.com/archives/CL7CM4BS6/p1585148848000900

**Comment by yichenroy** [comment]
ci:test:relevant

Restarting test, previous test failed for unrelated network issues.

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/jkappler/liferay-portal/pull/743

**Pull request closed without merging**
