### PR TITLE
LPS-83625 Buildlang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
cc @ealonso

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62636. [See changes here.](https://github.com/jkappler/liferay-portal/compare/8a50946ac93b~2...8a50946ac93b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62638. [See changes here.](https://github.com/jkappler/liferay-portal/compare/aea1dc65b6bf~2...aea1dc65b6bf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62640. [See changes here.](https://github.com/jkappler/liferay-portal/compare/8917c3970951~2...8917c3970951) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/64386. [See changes here.](https://github.com/jkappler/liferay-portal/compare/dc9cc7d89134~2...dc9cc7d89134) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
