### PR TITLE
LPS-109350 Regenerate

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
Your pull request test has been aborted. We are sorry of the inconvenience but QA is in the process of refining the `ci:test:relevant` test suite. Unfortunately this particular pull request test has exceeded the maximum resource limit and will be aborted. Please contact your team's QA representative(s) for next steps. If your team does not have one then please make a post in [#d-quality-assurance](https://liferay.slack.com/archives/CL84ZPHAT)

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
see: https://github.com/jkappler/liferay-portal/pull/762

**Pull request closed without merging**
