### PR TITLE
LPS-75898 - Close btn fix

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53017. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/53020. [See changes here.](https://github.com/jkappler/liferay-portal/compare/8115861~1...8115861) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
