### PR TITLE
LPS-86223 Baseline

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65537. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/65573. [See changes here.](https://github.com/jkappler/liferay-portal/compare/f12e86eb2ec1~1...f12e86eb2ec1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
