### PR TITLE
Experiences

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey @victorg1991 !!

Thanks a lot for this proposal, you have delivery it very fast.

I don't know exaclty how LayoutStructureCommonStylesCSSServlet.java should behave, but with this proposal, as the ServicePreAction is not being executed, you are not obtaining the current Structure of the Page, but the default one. It is OK?

What is the main goal for LayoutStructureCommonStylesCSSServlet?

Thanks!!

**Comment by victorg1991** [comment]
Hey @cgoncas LayoutStructureCommonStylesCSSServlet goal is to serve the CSS for the page styles. 

It receives the segmentExperienceId and the plid of the page by parameter, so it doesn't matter that the ServicePreActions is executed or not since it relies on the parameters. So in case the parameter is wrong we just rely on the default segment experience

**Comment by cgoncas** [comment]
> Hey @cgoncas LayoutStructureCommonStylesCSSServlet goal is to serve the CSS for the page styles.
> 
> It receives the segmentExperienceId and the plid of the page by parameter, so it doesn't matter that the ServicePreActions is executed or not since it relies on the parameters. So in case the parameter is wrong we just rely on the default segment experience

Hey @victorg1991 !!

But this is a bug behaviour, because we need to rely in the attribute that is only set in the ServicePreAction, otherwise, the page will render a different experience that the one used for the LayoutStructureCommonStylesCSSServlet.

**Comment by victorg1991** [comment]
ServicePreAction is used when generating the url for the servlet, (when rendering the page) so the segments experience id is good there. If the experience id is bad there there isn't much that we can do in this servlet other than relying on the default one

**Comment by cgoncas** [comment]
Hey @victorg1991 !!

The sergmentExperienceId is NOT set in the URL, the ServicePreAction doesn't change the URL, just add an attribute to the  HttpServletRequest.

**Pull request closed without merging**
