### PR TITLE
LPS-75540 page templates

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/p2kmgcl/liferay-portal/pull/28. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
