### PR TITLE
LPS-92603

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
```
		if (assetRendererFactory != null) {
			assetRendererFactory.getAssetRenderer(
				infoDisplayObjectProvider.getClassPK());
		}
```

That method doesn't make any sense because it's a getter that doesn't do anything.

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71266. [See changes here.](https://github.com/jkappler/liferay-portal/compare/cbce383a4af1~1...cbce383a4af1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71267. [See changes here.](https://github.com/jkappler/liferay-portal/compare/cbce383a4af1~1...cbce383a4af1) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71273. [See changes here.](https://github.com/jkappler/liferay-portal/compare/e76e174db8d6~3...e76e174db8d6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
