### PR TITLE
LPS-98571 Display new lines properly for error messages in fragment preview panel

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76158. [See changes here.](https://github.com/jkappler/liferay-portal/compare/9e0669ae5191~3...9e0669ae5191)

**Pull request closed without merging**
