### PR TITLE
[TS] LPS-107240

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-107240

From @wanderlast:

> Per, [PTR-1476](https://issues.liferay.com/browse/PTR-1476) this is being sent to Master first despite not being reproducible in Master due to a related regression.
> 
> This is mostly identical to the fix you sent me in https://github.com/wanderlast/liferay-portal-ee/pull/51, but adapted to Master by using the GroupItemSelectorCriterion. I've also included an extra semver commit that was previously missing. Please let me know if there's any other work you want me to do on this like a writeup of the issue for the PT. Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
hey @ChrisKian, will review this on Monday, thanks!

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
set to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/84061

**Pull request closed without merging**
