### PR TITLE
LPS-77721 Moves contextual-sidebar tag to frontend-taglib

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/55749. [See changes here.](https://github.com/jkappler/liferay-portal/compare/5fb8467~1...5fb8467) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
