### PR TITLE
LPS-100542 Adapt resolvers to take into account Web Content friendly urls with slashes

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78219. [See changes here.](https://github.com/jkappler/liferay-portal/compare/56e53f91c487~2...56e53f91c487)

**Pull request closed without merging**
