### PR TITLE
LPS-118788 Make sure the response is not null, otherwise freemarker compilation may fail if it contais a portlet

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
