### PR TITLE
LPS-89154 Remove unused code

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/292. [See changes here.](https://github.com/jkappler/liferay-portal/compare/8972a975f074~3...8972a975f074) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2103. [See changes here.](https://github.com/jkappler/liferay-portal/compare/ef15294e2c36~3...ef15294e2c36) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
