### PR TITLE
LPS-84836 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-84836

### CODE REVIEW

**Comment by kyle-miho** [comment]
./cc @brianchiu

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63233. [See changes here.](https://github.com/jkappler/liferay-portal/compare/cd6d1b98d873~2...cd6d1b98d873) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63271. [See changes here.](https://github.com/jkappler/liferay-portal/compare/b549ccc7ddac~3...b549ccc7ddac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
