### PR TITLE
[TECHNICAL-SUPPORT] LPS-97745

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-97745
https://issues.liferay.com/browse/PTR-1025

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test:sf

**Comment by JosemariaMunoz** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75879. [See changes here.](https://github.com/jkappler/liferay-portal/compare/08054145a751~3...08054145a751)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75881. [See changes here.](https://github.com/jkappler/liferay-portal/compare/de3e3a171585~3...de3e3a171585)

**Pull request closed without merging**
