### PR TITLE
LPS-93428 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-93428

### CODE REVIEW

**Comment by kyle-miho** [comment]
@jkappler this might not even be the best way to improve it, but i send it to you just in case since it didnt take that long.

**Comment by kyle-miho** [comment]
testing here https://github.com/kyle-miho/liferay-portal/pull/168

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70997. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
