### PR TITLE
LPS-27599 For now remove the title, will add methods for localized values

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @Preston-Crary, I'm stuck with an issue with integration tests.

- ManifestSummaryTest, since we clone the article, we should also clone the title, titleMap, description and descriptionMap?
- JournalArticleFinderTest (testQueryByG_F), it's using ArticleTitleComparator, and searches directly for title in the query (and in all the finders)

Any idea of how we could overcome this?

In case of upgrade process, front-end, staging, import-export, I tested and everything seems to be alright.

Thanks for the time!

@cc:/ @juliocamarero

**Comment by Preston-Crary** [comment]
Hi @jkappler,

sorry it'll be a couple days before I can take a look at this.  I'll try to get back to you as soon as I can.

Thanks!

**Comment by jkappler** [comment]
Thanks for the time @Preston-Crary!

**Comment by Preston-Crary** [comment]
Hi @jkappler,

For JournalArticleFinderTest, let's deprecate ArticleTitleComparator and remove it form the test.  This wasn't working in a meaningful way before the change (since it's just sorting XML and not the by the localized title) so I don't feel bad for removing it.

The clone in StagedModelDataHandler was added by LPS-27530 / 169c724.  I think we can ignore it in this case.  As long as the title when changed in the staging site does not update the live site without publishing and the live site is updated correctly when after publishing then everything should be working with this and staging.

Sorry again for the delayed response.

**Pull request closed without merging**
