### PR TITLE
LPS-104711 Check the parameter map for use of portletId and compare if it is using the actual portletId that is used on the page

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @jkappler 

This looks like a general issue with content pages, so I think it is better if you guys take a look at it. Let me know if you need anything.

Thanks!

/cc @SamZiemer @knchau

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
sent to @ealonso

**Pull request closed without merging**
