### PR TITLE
LPS-112527 Use layoutPrototype UUID to make LayoutPageTemplateEntry staging backwards compatible.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Pull request closed without merging**
