### PR TITLE
LPS-115640 When duplicating an item, build the fragment entry link object after saving the layout structure, DropZoneFragmentEntryProcessor relies on having the layoutStructure updated to generate the correct html because it is using the uuid of the generated layout structure items

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
