### PR TITLE
LPS-101134 Test convert for widget page with 1 column and multiple portlets

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/134. [See changes here.](https://github.com/jkappler/liferay-portal/compare/079aa5dee43c~2...079aa5dee43c)

**Comment by jkappler** [comment]
sent and merged, thanks

**Pull request closed without merging**
