### PR TITLE
LPS-101695 Do not pass the same categoryIds in the assetEntryQuery and as a parameter

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78465. [See changes here.](https://github.com/jkappler/liferay-portal/compare/f63f36bc19c0~1...f63f36bc19c0)

**Pull request closed without merging**
