### PR TITLE
[TECHNICAL-SUPPORT] LPS-105416

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@jonathanmccann, better send to @ealonso or @pavel-savinov. I'll be ooo for some weeks

**Comment by jonathanmccann** [comment]
https://github.com/ealonso/liferay-portal/pull/2641

**Pull request closed without merging**
