### PR TITLE
LPS-93766 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-93766

### CODE REVIEW

**Comment by kyle-miho** [comment]
Passed after changes: https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/44391/AXIS_VARIABLE=2,label_exp=!master/testReport/com.liferay.asset.service.test/AssetTagLocalServiceTest/testIncrementAssetCountWithAssetTagNameGreaterThan75/

Tested here: https://github.com/kyle-miho/liferay-portal/pull/171

Upstream failure: https://test-1-11.liferay.com/job/test-portal-acceptance-upstream-batch(master)/AXIS_VARIABLE=2,label_exp=!master/39279/testReport/junit/com.liferay.asset.service.test/AssetTagLocalServiceTest/testIncrementAssetCountWithAssetTagNameGreaterThan75/

**Comment by kyle-miho** [comment]
@cgoncas your integration test: AssetTagLocalServiceTest.testIncrementAssetCountWithAssetTagNameGreaterThan75
caught this! thanks!

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71476. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
