### PR TITLE
[TS] LPS-108113 Don't export AssetDisplayPageEntry object the second time _exportAssetDisplayPage code is executed to avoid a loop that causes a stackoverflow

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-108113

@dacousalr, thank you for your idea, it works fine!!

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
sent here: https://github.com/brianchandotcom/liferay-portal/pull/86589

**Pull request closed without merging**
