### PR TITLE
[TECHNICAL-SUPPORT] LPS-91578

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Hi @jonathanmccann, @knchau, I'm unsure about the fix in edit_article.jsp. Will check it out more in depth tomorrow

**Comment by knchau** [comment]
Hi @jkappler, have you gotten the chance to look at it any further?

**Comment by jkappler** [comment]
Hi @knchau, very little since we are working on other stories. But I think we should follow a different approach. And that is maybe passing the attribute in another place, but not in edit_article. 

Also, the second commit should be reviewed by the infrastructure team. It's not something that we can decide upon 

Sorry for the lack of updates on this

**Comment by knchau** [comment]
Hi @jkappler, no worries! I'll make those changes, but for clarification purposes, do you want the attribute to be passed from a different jsp file or just a different location entirely?

**Comment by jkappler** [comment]
@knchau, I just checked the issue again to be sure (just to corroborate something), and as I feared, this is not only a journal article issue. You can reproduce this in asset publisher, for example:

Instead of a WCD portlet, add an Asset Publisher to the page, and add blog, kb article, or any other assets that have permissions. You'll see that it will default to site member, not guest. So adding it to edit_article.jsp may solve the issue, but the real issue will persist......

I'm closing this for now, since it doesn't cover the root issue. I can take a look at it next week. For now, I'll reassign it again to you.   

Thanks, and sorry again for the delay

**Comment by knchau** [comment]
@jkappler, the changes that I made to InputPermissionsParamsTag.java solves the issue in asset publisher since asset publisher contains the correct referer plid. 

However, the WCD portlet sets referer plid to 0 when adding a content. Instead of passing the attribute in edit_article, would it be more fit to set the refererPlid in portal-impl/ServicePreAction.java?

Thank you!

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/332. [See changes here.](https://github.com/jkappler/liferay-portal/compare/f56f40b23acd~3...f56f40b23acd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
