### PR TITLE
LPS-80534 Update tests

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/preston-crary/liferay-portal/pull/530. [See changes here.](https://github.com/jkappler/liferay-portal/compare/0f4a365~2...0f4a365) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/165. [See changes here.](https://github.com/jkappler/liferay-portal/compare/8d95aeef6291~3...8d95aeef6291) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robertoDiaz** [comment]
@jkappler  ??????

**Comment by jkappler** [comment]
@robertoDiaz, had a branch named pr-165, and deleted it, please ignore this

**Pull request closed without merging**
