### PR TITLE
LPS-90960 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-90960

### CODE REVIEW

**Comment by kyle-miho** [comment]
Hey Jurgen, I tried to make these tests as clean and as stable as possible, would like to talk to you when you review it when you have a chance.

**Some Notes:**
1) I moved the original test (FragmentCollectionServiceTest) to localService instead, so you may see a lot of weird difference changes
2) I filled in the rest with tests for most of the impls for both remote and local service, so there should be a lot of more tests overall to look at.
3) Two of these integration tests should fail
```
testGetFragmentCollectionsByOrderByNameComparatorAndKeywordsAsc()
testGetFragmentCollectionsByOrderByNameComparatorAndKeywordsDesc()
```
I talked to you about this on slack before about how we don't use mysql '%' wildcards to allow the keyword filter to do substring filters.
[No wildcards](https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-service/src/main/java/com/liferay/fragment/service/impl/FragmentCollectionLocalServiceImpl.java#L196-L197)
[Wildcards](https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-service/src/main/java/com/liferay/fragment/service/impl/FragmentCollectionServiceImpl.java#L146-L148)

**How I designed the testcases**
1) If a remote service only calls the impl of a local service, but checks for permission, then we will do a permission test, and not check the functionality since it should have its own functionality test on the local level. If it has its own implementation, then we test that instead.
2) Continued with Persistence level fetches for the base addFragmentCollection() like in AssetListEntryAssetEntryRelServiceTest, with the purpose of not having the addFragmentCollection rely on another service like fetch or get.
3) If a testcase gets long, I would abstract some of the functionality into a function (permission addition for manage fragments), or split the testcase (asc / desc test) so that it still remains readable for other people and keeps it more maintainable.

**Comment by kyle-miho** [comment]
ci:test
cc: @brianchiu

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/71771. [See changes here.](https://github.com/jkappler/liferay-portal/compare/19e9432b2a29~4...19e9432b2a29) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
