### PR TITLE
[TECHNICAL-SUPPORT] LPS-88424

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @joshuacords 

Notes from Josh:

> https://issues.liferay.com/browse/LPS-88424
> https://issues.liferay.com/browse/LPP-32391
> 
> Most of the changes is simply converting the methods to dynamic queries, there is some minor optimizations included. I choose 1000 as the interval because in testing a DB2 Database with logs set to:
>  logprimary = 3 and logsecond = 10 (which is a default setting) was failing to complete these transactions long before the 10,000 standard interval. However, with the interval of 1000, it was passing.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
hey @SamZiemer, I'm ooo until 01/10, better send to @dacousalr, @ealonso or @pavel-savinov

**Comment by jkappler** [comment]
CC: @joshuacords

**Comment by SamZiemer** [comment]
@jkappler. I apologize. I missed your comment. I have forwarded this pull request to https://github.com/dacousalr/liferay-portal/pull/86

**Pull request closed without merging**
