### PR TITLE
LPS-110892 Export fragment compositions or entries ID array can be null here

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:stable

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant, SB fix merged to upstream

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
@xbrianlee @patriciajeanperez Should Jurgen quarantine or retest `ViewPortalSmokeArchive621021`?
```
     [exec]     LIFERAY_ERROR: Duplicate entry '10155-1-0-com_liferay_users_admin_web_portlet_MyOrganizationsPor' for key 'IX_CB778855'
     [exec]     LIFERAY_ERROR: Unable to initialize My Account panel permissions for portlet com_liferay_users_admin_web_portlet_MyOrganizationsPortlet in company 10155
```

**Comment by xbrianlee** [comment]
@jpince This looks like a race condition causing duplicate entries in the database, not a Search issue. I would probably retest in this situation.

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
will be retested here: https://github.com/jkappler/liferay-portal/pull/744

**Pull request closed without merging**
