### PR TITLE
LPS-108211 SF

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@IstvanD, @dacousalr, will wait after GA2 is out to send the PR to Bchan. Sorry for the wait

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by IstvanD** [comment]
Hi @jkappler 

Please note that I added a commit to the solution
https://github.com/dacousalr/liferay-portal/pull/197/commits/83d52034cfdb431d674b17c4f9d280cb8c28c1cb

**Comment by dacousalr** [comment]
Hi @jkappler,

After clarifying the commit @IstvanD mentioned, you can continue to review this PR taking only into account the commits of this PR.

If you don't agree, please, let me know.

Best

**Comment by IstvanD** [comment]
Hi @jkappler, @dacousalr 

Please see my comment https://github.com/dacousalr/liferay-portal/pull/197#issuecomment-601750211

Thank you and best regards,
István

**Comment by jkappler** [comment]
Sent and merged here: https://github.com/brianchandotcom/liferay-portal/pull/86701

Thanks

**Pull request closed without merging**
