### PR TITLE
LPS-110789 Move to corresponding method and apply to master pages too

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
bundled here: https://github.com/jkappler/liferay-portal/pull/742

**Pull request closed without merging**
