### PR TITLE
LPS-89648

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-89648

In order to test this issue in master, you'll need to create a new AssetRenderer class and implement it without a portletId.  You can see my changes are safe, because the default action if we cannot retrieve the resourceBundle from the portlet bag is to simply return the className.

Please let me know if you have any questions.  Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/preston-crary/liferay-portal/pull/663. [See changes here.](https://github.com/jkappler/liferay-portal/compare/c7a0d8d6af69~1...c7a0d8d6af69) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
