### PR TITLE
LPS-93807 Change the way we get the title to avoid errors in tests

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/72464. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchiu/liferay-portal/pull/1884. [See changes here.](https://github.com/jkappler/liferay-portal/compare/92f4f864b124~1...92f4f864b124) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
