### PR TITLE
LPS-92769 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-92769

### CODE REVIEW

**Comment by kyle-miho** [comment]
Testing here: https://github.com/kyle-miho/liferay-portal/pull/161
Not sure if this works bc the content page editor is broken. It is possible, but to me highly unlikely that this caused it. Maybe language keys work differently for js files? (Uses Liferay.Language.get() instead of LanguageUtil.get()). But i would only expect the key to not get translated if the implementation is different and not break the sidebar.

**Comment by kyle-miho** [comment]
Recompiled, the sidebar failure is likely either upstream, or i am on a bad commit

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/70370. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
