### PR TITLE
LPS-110938 Extract to method and simplify with early exit

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:stop

@jkappler 
> David Gutierrez:house:  1 hour ago
I think that test is broken https://issues.liferay.com/browse/LRQA-57212
Can you just please ignore it?
https://liferay.slack.com/archives/CL84ZPHAT/p1585319470079900?thread_ts=1585318750.077400&cid=CL84ZPHAT

cc/ @david-gutierrez-mesa is there a way to identify consistent failures like this earlier? It would save time for the developers and save CI resources as well.

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
https://github.com/jkappler/liferay-portal/pull/756

**Pull request closed without merging**
