### PR TITLE
LPS-102821 Adapt test macro openDisplayPagesAdmin

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79746. [See changes here.](https://github.com/jkappler/liferay-portal/compare/a9cc45eff0e3~7...a9cc45eff0e3)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79750. [See changes here.](https://github.com/jkappler/liferay-portal/compare/97780772bb7f~7...97780772bb7f)

**Pull request closed without merging**
