### PR TITLE
LPS-154713 Use language keys in cookies banner and consent configurations

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-154713 Change configuration class accordingly, now that we can set language keys as default values
- LPS-154713 Build lang

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@oliverkecskemety

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by gaborlovasdotcom** [comment]
ci:test:cookies

**Comment by jkappler** [comment]
thanks @gaborlovasdotcom!

**Comment by jkappler** [comment]
ci:test:cookies

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@gaborlovasdotcom, cookie tests pass, so forwarding it

**Pull request closed without merging**
