### PR TITLE
LPS-108454 Revisit PageDefinition format

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
Goes on top of https://github.com/pavel-savinov/liferay-portal/pull/517

**Comment by ruben-pulido** [comment]
fyi (@nhpatt)

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
