### PR TITLE
Lps 28940 upgrade youtube portlet to a generic video embedder

### PR DESCRIPTION
**Pull request by arthurchan35**
from https://github.com/ealonso/liferay-portal/pull/1164

@jkappler 
Really sorry for the delay, it turned out I lost my code local and remote, so I had to rewrite all the commits with help from a decompiler. I tried my best to recover all the commits structure and information as much as I can.

To your question:
I think its better to update youtube bundle information, so we can have a track of it. Plus I am writting this one base on the original youtube portlet.
It would be redundant to have two portlets, video embedder and youtube, because this video embedder has all the functionalities from youtube portlet plus more.
But again, I am bit scared to modify all the bundle infomation, bnd information, package names, etc, since I am not familiar with it. If I can have some guidance, I will be glad to make this change. Or if you can give a help, that will be great too!

### CODE REVIEW

**Comment by jkappler** [comment]
Thanks @arthurchan35, will take a look at it

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:retest

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Hi @arthurchan35. One quick question: have you noticed that SF doesn't work correctly in this branch?

I'm seeing a lot of code that is not formatted, for example:

```
@Override
public String getPresetRatio() {
	if (presetRatio != null) {
		return presetRatio;
	} presetRatio = portletPreferences.getValue("presetRatio", "16:9");

	return presetRatio;
} 
```

in BaseVideoEmbedderDisplayContext.java

**Comment by arthurchan35** [comment]
@jkappler
It's also weirld to me, I just ran gradle sorce formatter again and it didnt complain about anything, so I went to talk to Hugo and he said "Nothing wrong with your branch. SF simply not catching that case. I'll get that added to SF"

**Pull request closed without merging**
