### PR TITLE
LPS-96149 Ensure destructor method is called to remove any remaining handler

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/389. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
