### PR TITLE
LPS-94910 Use JSP-based fragment portlet renderer to render widgets in content pages

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@JorgeFerrer Sigo pensando que incluir esto en la release es peligroso.

/cc @ealonso

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchiu/liferay-portal/pull/1915. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchiu/liferay-portal/pull/1916. [See changes here.](https://github.com/jkappler/liferay-portal/compare/6fe081364a58~1...6fe081364a58) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
