### PR TITLE
LPS-75549

### PR DESCRIPTION
**Pull request by alessiorendina**
Fixed screen navigation issue.

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alessiorendina** [comment]
@jkappler The case is here: https://github.com/marco-leo/com-liferay-commerce-private/pull/308
Marco is reviewing it.

**Comment by jkappler** [comment]
Thanks @Commando18 !

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/52648. [See changes here.](https://github.com/jkappler/liferay-portal/compare/1a819f2~2...1a819f2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
