### PR TITLE
[TECHNICAL-SUPPORT] LPS-100472 Hide display page template selection for global web contents

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @jkappler ,

When editing a Global scoped web content that is displayed in a site's scope, the editor allowed users to select Display Pages from the site's scope. However, this should not be possible:
1. Global scope can't have any display pages (either Display Page Template or Pages with default Asset Publisher)
2. The display page of the web content should be in its own site

Therefore, global web contents are not allowed to have display pages.
This is not a problem for non-global contents, since they are always edited in their own scope. The reason why global contents are different is described in [this LPS comment](https://issues.liferay.com/browse/LPS-100472?focusedCommentId=1950138&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1950138).

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by vendeltoreki** [comment]
Hi @jkappler ,

I just realized that ThemeDisplay can be directly acquired from ServiceContext as well: https://github.com/jkappler/liferay-portal/pull/595/files#diff-4ed8c71f6aa7210442beb1bcf738de08R62
That would simplify things a little bit.

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78341. [See changes here.](https://github.com/jkappler/liferay-portal/compare/8f3ed5e44973~2...8f3ed5e44973)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78344.

**Pull request closed without merging**
