### PR TITLE
LPS-78661 Use lang merger where ADTs are used

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test

**Comment by jkappler** [comment]
hey @kyle-miho, it's interesting, no forms errors this time...could it have been an isolated issue?

**Comment by kyle-miho** [comment]
@jkappler possibly.. I'll run ci again to make sure!

**Comment by kyle-miho** [comment]
ci:test:relevant

**Pull request closed without merging**
