### PR TITLE
LPS-88355 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-88355

### CODE REVIEW

**Comment by kyle-miho** [comment]
@jkappler fyi: one integration test is currently failing 
testMoveAssetListEntryAssetEntryRelToOccupiedPosition() because this registered callback
```
TransactionCommitCallbackUtil.registerCallback(
			() -> {
				assetListEntryAssetEntryRel.setPosition(newPosition);

				assetListEntryAssetEntryRelLocalService.
					updateAssetListEntryAssetEntryRel(
						assetListEntryAssetEntryRel);

				swapAssetListEntryAssetEntryRel.setPosition(position);

				assetListEntryAssetEntryRelLocalService.
					updateAssetListEntryAssetEntryRel(
						swapAssetListEntryAssetEntryRel);

				return null;
			});
```
does not get executed before we make this assertion below. I am not sure how to force the callback or what executes it.
```
		//assert assetListEntryRels swap positions

		Assert.assertEquals(
			originalPosition, assetListEntryRelOccupied.getPosition());

		Assert.assertEquals(
			occupiedPosition, assetListEntryRelOriginal.getPosition());
```
Also I added one seperate commit with a comment that will convey intent of an assertion. I wasn't sure if the assertion is too vague, so I added it, but if you think the comment is un-necessary still, feel free to remove it.

**Comment by kyle-miho** [comment]
ci:test

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/145. [See changes here.](https://github.com/jkappler/liferay-portal/compare/44297c59bd70~6...44297c59bd70) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
