### PR TITLE
LPS-85311

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/63189

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63193. [See changes here.](https://github.com/jkappler/liferay-portal/compare/f0cf90b0fc44~1...f0cf90b0fc44) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63223. [See changes here.](https://github.com/jkappler/liferay-portal/compare/c9d583e473d4~1...c9d583e473d4) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
