### PR TITLE
LPS-110712 Avoid exporting assetEntries more than once

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
Sent to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/86772

**Comment by jorgediaz-lr** [comment]
ci:stop

**Pull request closed without merging**
