### PR TITLE
LPS-98042 Site administrators cannot create Widget Page Templates

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76023.

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/544. [See changes here.](https://github.com/jkappler/liferay-portal/compare/753271e80df8~1...753271e80df8)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76254. [See changes here.](https://github.com/jkappler/liferay-portal/compare/d8c1996518eb~3...d8c1996518eb)

**Pull request closed without merging**
