### PR TITLE
LPS-96190 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-96190
cc: @brianchiu This should cover permissions for fragmentEntryLinks since the front-end uses the remote services to test permissions. https://issues.liferay.com/browse/LPS-96046

### CODE REVIEW

**Comment by kyle-miho** [comment]
Some things to note:

1) When using persistence calls to verify data (to avoid dependency on fetch/get service), we need to **always remember to include PersistenceTestRule.INSTANCE**. For some cases we will not need this, but if we create any assetEntry, this will cause an error because there is a callBack created in assetEntryAutoTagger, which takes too long to actually commit (after) _group is deleted if we fail to includ PersistenceTestRule.INSTANCE
2) We need to actually create a layout in order to check permissions. Since we check the base model of the classNameId/classPK(layout.class + plid) to see if the user can edit the fragmentEntryLink, the layout has to actually exist, so we have to create it otherwise the permissionChecker will think the user does not have permissions to edit it, when in fact the layout does not exist.
3) Because of 2), I had to import com.liferay.portal.util.test.LayoutTestUtil; I'm not sure if I needed to actually include it in the build.gradle, since it seemed to compile fine without it, maybe its included in portal-impl/portal-kernel even though the package name is different?

Bonus) this actually gains us a LOT of good coverage since testing permissions through functional tests take a lot of time to make, are very slow, and are not very stable, and this would cover the base services.

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Note that this pull depends on : https://github.com/pavel-savinov/liferay-portal/pull/377

Othewise, it will have a failing test

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/74912. [See changes here.](https://github.com/jkappler/liferay-portal/compare/053f0811c806~1...053f0811c806) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
