### PR TITLE
LPS-83928 Debounce added to rowToggled event handler to avoid multiple calls

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62312. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
