### PR TITLE
LPS-103676 Embedded page does not show URLs without "http://" correctly

### PR DESCRIPTION
**Pull request by knchau**
https://issues.liferay.com/browse/LPS-103676

Not sure if this would make a drastic to the performance issue you mentioned in the previous PR, but I used a different getLayouts() that narrows down the layouts to its groupId and privateLayout. This is because the embedded page cannot use the friendly url of a page outside its groupId and it cannot use the friendlyURL of a private page. 

Please let me know your thoughts on this or any further suggestions you might have. 

Thank you!!

### CODE REVIEW

**Comment by knchau** [comment]
ci:test:sf

**Comment by knchau** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
We went with another approach, sent here: https://github.com/brianchandotcom/liferay-portal/pull/81407

Thanks for everything @knchau!

**Pull request closed without merging**
