### PR TITLE
[TECHNICAL-SUPPORT]  LPS-99067

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-99067

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test:sf

**Comment by JosemariaMunoz** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76403.

**Pull request closed without merging**
