### PR TITLE
LPS-99529 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-99529

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
@jkappler If you remember the conversation in the slack channel that we should seperate display page tests outside of content page templates (display pages have no layoutPageTemplateCollectionId, and when used more extensively will have classNameId and classTypeId set). Eudaldo said it was okay to treat the naming of them as displayPageTemplate, so I am using that name.

There is an added dependency on ddm api, however I think its necessary if we want to truly test display page instead of creating a mock ddmStructure (also in case that gets verified and causes the test to fail).

Maybe it is a good idea to eventually actually import journal-api and test displayPages with journal in the future.

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77424.

**Pull request closed without merging**
