### PR TITLE
LPS-144162 Fix team extranet broken links

### PR DESCRIPTION
**Pull request by atjuan**

### CODE REVIEW

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Awesome @atjuan, thanks for the PR

**Comment by atjuan** [comment]
ci:test:sf

**Comment by atjuan** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
