### PR TITLE
LPS-87908

### PR DESCRIPTION
**Pull request by dacousalr**
\cc @laszlopap

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/159. [See changes here.](https://github.com/jkappler/liferay-portal/compare/509a0fc78717~1...509a0fc78717) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
