### PR TITLE
LPS-96689 Adapt unit tests

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76256.

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76258.

**Pull request closed without merging**
