### PR TITLE
LPS-65079 Fix class name reference in DDM upgrade

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
@vicnate5, is this a known issue or cause by this pull?

**Comment by vicnate5** [comment]
@marcellustavares There is an issue with our tests that run on portal instances that we are currently looking into. The test failure is not caused by this pull.

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
@marcellustavares, the issue persists. It seems that when upgrading JournalStructure it's not creating the composite key :(

**Comment by jkappler** [comment]
@marcellustavares, works perfectly, had to clean cache and everything (my bad). Will send right away :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/38966. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
