### PR TITLE
LPS-84890 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-84890

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test

**Comment by kyle-miho** [comment]
ci:test

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/pavel-savinov/liferay-portal/pull/218. [See changes here.](https://github.com/jkappler/liferay-portal/compare/f185d1ea3c2f~2...f185d1ea3c2f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/62668. [See changes here.](https://github.com/jkappler/liferay-portal/compare/ef858049c91b~4...ef858049c91b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
