### PR TITLE
LPS-79911 Buildlang

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1613. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/kyle-miho/liferay-portal/pull/150. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
