### PR TITLE
LPLS-114731 Generalize InfoItemReference to support searching by friendlyURL and key in addition to classPK

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Hey @jkappler, @csierra, @4lejandrito,

Here is a proposal to generalize the way to identify infoItems and also how keep a reference to them. These are the highlights of this proposal:

1) I have renamed the recently added InfoItemReference as InfoItemIdentifier

I did this because we already had InfoItemClassPKReference which has a slightly different purpose since it contains the className. I considered adding className to InfoItemReference, but that wouldn't make sense since where it's used the className is already known. So I settled on the following semantics:
- Identifier: it's a way of identify an item for a known entity type (aka className)
- Reference: it's a reference to an item and incldues the type (className) and the identifier.

2) I created a subclass of InfoItemIdentifier called ClassPKInfoItemIdentifier and made the parent abstract

This change allows us to create other types of identifiers such as by:
a. Group and Key
b. Group and friendlyURL
c. ERC

One thing I'm not fond of right now is that I have had to modify the Object Providers to do an instanceof check and throw an exception when an unsupported type of Item Identifier is used by the consumer. What I don't like is that the consumer doesn't have any way to determine if the identifier that it has is supported by an Object Provider. I've thought of several solutions but I'm not conviced with any of the yet:
a. Add a method called supportsInfoItemIdentifier(InfoItemIdentifier) but I'm not in love it it.
b. Split the ObjectProvider interface into several. One per type of identifier. Doing this lets the compiler check the compatibility, but it makes it harder to treat the identifiers in a generic way, which I tend to think will be useful.

3) To showcase the generalization I've created GroupKeyInfoItemIdentifier

I have also implemented support for it in JournalArticleInfoItemObjectProvider since Journal articles have the concept of a group-scoped unique key.

NOTE: I didn't have time to write a test yet. But we should add it before committing this to master or as soon as possible afterwards.

4) I also ended up creating a third type of identifier: GroupUrlTitleInfoItemIdentifier

Jurgen, this could actually also help for the ongoing task of finishing the replacement of InfoDisplayContributor

5) I have generalized InfoItemClassPKReference into InfoItemReference which leverages InfoItemIdentifier

I have taken several steps to facilitate keeping backwards compatibility:
a. I made InfoItemClassPKReference a subclass of InfoItemReference (even though I deprecated it)
b. I added a constructor to InfoItemReference for the common case of a classPK identifier
c. I added a method getClassPK() ==> This is something I'm not particularly fond of because it will return 0 in cases where the identifier is not a ClassPKInfoItemIdentifier

6) I had to made some changes to translations classes

Alex, I did my best to make the right changes, but please double check.

SIDE NOTE: this pull also has a commit that fixes what I think is a bug related to versioning in JournalArticleInfoItemProvider. @jkappler, please double check

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
I did push force after rebasing and having to resolve a conflict

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
