### PR TITLE
LPS-117534 Set cursor pointer for cards

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
@p2kmgcl

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1673

**Pull request closed without merging**
