### PR TITLE
LPS-27599 Upgrade process

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @Preston-Crary, this is the branch in which we are working for the localization columns. Just wanted to check with you if we are on the right track or not before continuing. Let us know what you think please. Thanks!

cc:/ @juliocamarero, @ealonso

**Comment by Preston-Crary** [comment]
For 5915ca9, let's try to reduce the number of columns as much as possible.  We also should add a defaultLanguageId column to JournalArticle as this was tracked by the document before.  Let's also set local-service="false" and remote-service="false" for JournalArticleLocalization.

```
<entity local-service="true" name="JournalArticle" remote-service="true" trash-enabled="true" uuid="true">

	.
	.
	.

	<column name="defaultLanguageId" type="String" />
	
	.
	.
	.

</entity>

.
.
.

<entity local-service="false" name="JournalArticleLocalization" remote-service="false">

	<!-- PK fields -->

	<column name="articleLocalizationId" primary="true" type="long" />

	<!-- Audit fields -->

	<column name="companyId" type="long" />

	<!-- Other fields -->

	<column name="articlePK" type="long" />
	<column name="title" type="String" />
	<column name="description" type="String" />
	<column name="languageId" type="String" />

	<!-- Finder methods -->

	<finder name="ArticlePK" return-type="Collection">
		<finder-column name="articlePK" />
	</finder>
	<finder name="A_L" return-type="JournalArticleLocalization" unique="true">
		<finder-column name="articlePK" />
		<finder-column name="languageId" />
	</finder>
</entity>
```


For 4ad3cb3 what happens when a translation isn't available for an article?  I'm not sure how we want to sort it.  We may even want to add a search for articles where we can find ones that don't have a translation for a given language.

In 75acc9a, instead of iterating over all the available locales.  Let's iterate over the keyset for the titles and then separately for the descriptions, it's possible that we have stored some that are not configured and it's also possible that some descriptions are localized without a localized title.

In b83027a and b509201, also override JournalArticleImpl.getDescription(String languageId, boolean useDefault). We should also override JournalArticleLocalizationImpl.getDescription and JournalArticleLocalizationImpl.getTitle to fall back to the default locale if the value is blank.

In f2182e2, let's us AutoBatchPreparedStatementUtil.concurrentAutoBatch. This should not cause a deadlock since we are doing only inserts.

**Comment by jkappler** [comment]
Thanks @Preston-Crary, working on the changes

**Comment by jkappler** [comment]
Closed in favor of https://github.com/jkappler/liferay-portal/pull/114

**Pull request closed without merging**
