### PR TITLE
LPS-99927 Fix query, the previous one was generated with field "title_sortable" which is not saved in Journal article's elastic search document

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77149. [See changes here.](https://github.com/jkappler/liferay-portal/compare/3b36e42ff78c~1...3b36e42ff78c)

**Pull request closed without merging**
