### PR TITLE
LPS-161850

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Hi @rotty3000, sorry for the lack of news, has been a very busy week. 

I managed to test and all looks good. I wanted to resend to the core infra team (liferay-core-infra) for a final review, but according to their guidelines we should also include tests for any pulls that we send them (if possible). 

Would it be possible to add a test for this, then we can send them the PR.

Thanks!

**Comment by rotty3000** [comment]
I'll try to add a test this week.

**Comment by jkappler** [comment]
thanks @rotty3000!

**Comment by rotty3000** [comment]
Note that this PR is now dependent on some forwarded changes to bchan. So please let's wait until those are reviewed and I will then make a further update for the completed test case.

**Comment by jkappler** [comment]
OK, thanks @rotty3000!

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
@jkappler this is now ready for your review again with a test.

**Comment by rotty3000** [comment]
ci:test:sf

**Comment by rotty3000** [comment]
odd... I will do a full and all after rebasing on master today...

**Comment by rotty3000** [comment]
ci:stop

**Comment by rotty3000** [comment]
ci:test:sf

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Hi @rotty3000, I will fix the compileTestIntegrationJava issue and send to core infra Team in a while. I'll cc you on it.

Thanks!

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@rotty3000, it's the issue I mentioned:

```
java.lang.BootstrapMethodError: java.lang.LinkageError: loader constraint violation: loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) previously initiated loading for a different type with name "org/osgi/service/cm/ConfigurationAdmin"
  at com.liferay.portal.test.function.CreatingFactoryConfigurationHolder.<init>(CreatingFactoryConfigurationHolder.java:29)
  at com.liferay.portal.instances.test.PortalInstancesConfigurationFactoryTest.testCreateVirtualInstanceFromFactory(PortalInstancesConfigurationFactoryTest.java:72)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by rotty3000** [comment]
yeah @jkappler sorry, I'll need a little time to figure out what's happening. please leave it with me until next week. thx for your efforts.

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
I think I'm getting closer...

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
Ok there just seems to be some logging which needs to be accounted for.

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Hi @rotty3000, seems that some classes are not available anymore and base line is needed:

import com.liferay.portal.test.function.CloseableHolder;
import com.liferay.portal.test.function.ConfigurationHolder;
import com.liferay.portal.test.function.CreatingFactoryConfigurationHolder;

From SF and code all looks good (after fixing those issues). 

I have transitioned to another engineering team, so please feel free to send the PR directly to core infra to review (https://github.com/liferay-core-infra)

Thanks!

**Comment by rotty3000** [comment]
Yeah this was refactored upstream. I'll fix it and resend this week.

**Pull request closed without merging**
