### PR TITLE
LPS-110790 Don't try to add fragment entry link if no fragment entry is found

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant, SB fix merged to upstream

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Bundled here: https://github.com/jkappler/liferay-portal/pull/742

**Pull request closed without merging**
