### PR TITLE
LPS-99619 buildLang

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
@jkappler Can you tell brian to not backport this? I will take care of it when its fully tested

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76860. [See changes here.](https://github.com/jkappler/liferay-portal/compare/280c81036bfd~2...280c81036bfd)

**Pull request closed without merging**
