### PR TITLE
LPS-97542 also checking the group id

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/linolaoj/liferay-portal/pull/189. [See changes here.](https://github.com/jkappler/liferay-portal/compare/cd6db31aa21e~1...cd6db31aa21e)

**Pull request closed without merging**
