### PR TITLE
LPS-98193 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-98193

### CODE REVIEW

**Comment by kyle-miho** [comment]
Hey Jurgen, I used helper methods to populate the entities bc 
1) rather not import test modules (if we want to simplify) from other modules if not needed since we use fragments as well
2) readability for others

------------------------------
Combining this pull with https://issues.liferay.com/browse/LPS-98138
to avoid the chance that the pulls get sent in separately and a publish occurs in between causing a semvar issue

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
@jkappler this is probably a bug with staging synchonization, ill try to see if i can fix it before i leave

**Comment by kyle-miho** [comment]
Problem is here: 
https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-page-template-service/src/main/java/com/liferay/layout/page/template/service/impl/LayoutPageTemplateEntryLocalServiceImpl.java#L292-L305
When deleting a Display Page, there seems to be a case where the DDM Structure Link is already deleted. I'm having trouble reproducing this, but thats the issue on CI.

Likely 2 possibilities 1) check if DDM Structure Link exists before deleting it.
1 could possibly be a bandaid approach
2) Find out what deletes the StructureLink bfeorehand and see if it should be deleting it. This likely requires more investigation to make the best possible fix

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/75690.

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Pull request closed without merging**
