### PR TITLE
LPS-89647 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-89647

### CODE REVIEW

**Comment by kyle-miho** [comment]
Testing here: https://github.com/kyle-miho/liferay-portal/pull/130

**Comment by kyle-miho** [comment]
Hey Jurgen! While creating site navigation menu service tests, I noticed that we still have the service addDefaultSiteNavigationMenu() and a helper function for it. With the (relatively) new change to how we don't automatically create site navigation menus anymore for the user because Public Pages Hierarchy is the new default for 7.1 / 7.2, I removed the service/helper function because it only takes up space now.

Feel free to keep it if you guys still want to keep it still, I just sent this to you in the case that it will be preferable to remove it. I can definitely see value in allowing the user to create a "starter" navigation menu based off the Public or Private Pages Hierarchy  (in which case we may want to keep these or just revert these commits in the future)

**Comment by kyle-miho** [comment]
Oops, I also forgot to run gradlew formatSource (there are some imports no longer needed), but I am off work for the day

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67413. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/67487. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
