### PR TITLE
LPS-96689 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-96689

### CODE REVIEW

**Comment by kyle-miho** [comment]
@ruben-pulido @jkappler fixed the serviceTest integration failures. 
com.liferay.fragment.internal.validator.FragmentEntryValidatorImplTest should have 2 unit tests failing, likely need to fix them.

I did find a bug when publising a fragment with invalid config (no error message displayed in UI)

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/100. [See changes here.](https://github.com/jkappler/liferay-portal/compare/ff2ec9714fd0~3...ff2ec9714fd0)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/ruben-pulido/liferay-portal/pull/102. [See changes here.](https://github.com/jkappler/liferay-portal/compare/78122933d806~3...78122933d806)

**Pull request closed without merging**
