### PR TITLE
LPS-90273 Build lang in portal-impl

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:sf

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by kyle-miho** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
