### PR TITLE
LPS-97702 --DISCARD ME-- Test data

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76351.

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76362. [See changes here.](https://github.com/jkappler/liferay-portal/compare/4545596a1f71~1...4545596a1f71)

**Pull request closed without merging**
