### PR TITLE
LPS-96689 Before rendering a fragment validate configuration and return detailed error information if invalid

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:test:relevant <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/76164. [See changes here.](https://github.com/jkappler/liferay-portal/compare/4b69651ab2a3~2...4b69651ab2a3)

**Pull request closed without merging**
