### PR TITLE
LPS-118276 Show AssetEntry-related info field values when using wrapper for the FileEntry entities

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by JorgeFerrer** [comment]
As I mentioned to @jkappler I think this solution is ok if we go ahead with the plan to move com.liferay.info.display out of info-api (and info-impl) and into its own modules: info-display-api and info-display-impl. The goal of this move is to isolate into these two new modules the things that we are planning to deprecate.

**Comment by JorgeFerrer** [comment]
Taking a bit closer loop, I've noticed that the dependency on assets is only for info-impl and not info-api, so I think it's fine if you guys want to got ahead with this pull. We can always remove the dependency later on. 
Still, I believe that a more permanent solution would be to implement InfoItemFormProvider and related services for FileEntry.

**Comment by jkappler** [comment]
thanks @JorgeFerrer!

for now I'll run relevant, and see if everythings okay

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
