### PR TITLE
LPS-76845 Uses the new table

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by jkappler** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/93. [See changes here.](https://github.com/jkappler/liferay-portal/compare/6c5c9cb~4...6c5c9cb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/jkappler/liferay-portal/pull/94. [See changes here.](https://github.com/jkappler/liferay-portal/compare/c71204c~4...c71204c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/1434. [See changes here.](https://github.com/jkappler/liferay-portal/compare/078ef3f~2...078ef3f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
